USE MASTER;

IF EXISTS (SELECT NAME FROM SYSDATABASES WHERE NAME='FIRE_INCIDENT')
BEGIN
  ALTER DATABASE FIRE_INCIDENT SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
  DROP DATABASE FIRE_INCIDENT;
END

CREATE DATABASE FIRE_INCIDENT;
GO